# Generated by Django 3.1.4 on 2020-12-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=350)),
                ('author', models.CharField(max_length=50)),
                ('timeStamp', models.DateField(blank=True)),
            ],
        ),
    ]
